# Pytorch


<p>Tensors are a data type just like lists, strings etc.<br>
We can convert numpy arrays into tensors and vice versa.<p>

In [12]:
# Importing PyTorch
import torch

In [6]:
# Initiating an empty tensor
# Single element like a scalar
x = torch.empty(1)
print(x)

tensor([0.])


In [7]:
x = torch.empty(3)
print(x)

tensor([0., 0., 0.])


In [8]:
x = torch.empty(2, 3)
print(x)

tensor([[-6.7504e+35,  1.7012e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [10]:
x = torch.empty(2, 3, 4)
x

tensor([[[-6.8540e+35,  1.7012e-42,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]])

In [11]:
# Random tensor
x = torch.rand(2, 3)
print(x)

tensor([[0.4588, 0.9079, 0.8389],
        [0.5571, 0.5396, 0.2206]])


In [13]:
# Ones tensor
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [21]:
# Ones tensor with specific data type, e.g. float
x = torch.ones(2, 3, dtype=torch.float)
print(x)
print(x.dtype)

# Finding the size of a tensor
print(x.size())
print(x.shape)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.float32
torch.Size([2, 3])
torch.Size([2, 3])


In [22]:
# Making tensors from data, e.g. lists
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [32]:
# Operations on tensors
x = torch.rand(2, 2)
y = torch.rand(2, 2)
# print(x, y)

z = x + y
w = torch.add(x, y)

# Element-wise addition
# print(z)
# print(w)

# In-place addition
y.add_(x)
print(y)

# Similarly, subtraction
# z = x - y

# Note: Any operation that mutates a tensor in-place is post-fixed with an _.

tensor([[0.7227, 1.1214],
        [1.4117, 0.7687]])
tensor([[0.7227, 1.1214],
        [1.4117, 0.7687]])
tensor([[0.7227, 1.1214],
        [1.4117, 0.7687]])


In [45]:
# Multiplication (element-wise)
z = x * y
print(x)
print(y)
# print(z)

# Division (element-wise)
w = x / y
print(w)

tensor([[0.8988, 0.2231],
        [0.0349, 0.9078]])
tensor([[0.3554, 0.6494],
        [0.6931, 0.2071]])
tensor([[2.5293, 0.3435],
        [0.0503, 4.3825]])


In [48]:
# Slicing tensors
x = torch.rand(2, 3)
print(x)
print(x[:, 0]) # all rows, first column
print(x[1, :]) # second row, all columns
# print(x[1, 1])


tensor([[0.4161, 0.0916, 0.0223],
        [0.5184, 0.7228, 0.3701]])
tensor([0.4161, 0.5184])
tensor([0.5184, 0.7228, 0.3701])


In [54]:
# reshaping tensors
x = torch.rand(4, 4)
print(x)

# Reshaping to 16 elements in a single dimension
# Use the view() method
y = x.view(16)
print(y)

# Reshaping to 2 rows and 8 columns
y = x.view(-1, 8)
# Note: -1 means automatically infer the number of remaining dimensions

tensor([[0.2277, 0.0945, 0.5357, 0.2852],
        [0.7776, 0.9837, 0.0961, 0.4904],
        [0.1358, 0.7923, 0.2274, 0.7849],
        [0.8201, 0.7624, 0.8964, 0.9559]])
tensor([0.2277, 0.0945, 0.5357, 0.2852, 0.7776, 0.9837, 0.0961, 0.4904, 0.1358,
        0.7923, 0.2274, 0.7849, 0.8201, 0.7624, 0.8964, 0.9559])


-----

### Numpy to Tensors and Vice Versa

In [61]:
import numpy as np
import torch

a = torch.ones(5)
# print(a)

b = a.numpy()
print(b)
print(type(b))

# Note: The numpy array and the torch tensor share the same memory location if they are on the CPU


[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


In [67]:
# Converting numpy arrays to torch tensors
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

a += 1
print(a)
print(b) # b also gets updated when a is updated
# Note: The numpy array and the torch tensor share the same memory location if they are on the CPU

b += 1
print(b)



[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


1. If the tensor is on the GPU, then the numpy array will be a copy of the tensor 
2. This is because numpy does not support GPU computations
3. To move a tensor to the GPU, use the .to() method <br>
    e.g. tensor.to('cuda')
4. To move a tensor back to the CPU, use the .to() method <br>
    e.g. tensor.to('cpu')
5. To move a tensor to the GPU if available, use the .cuda() method <br>
    e.g. tensor.cuda()
6. To move a tensor to the CPU, use the .cpu() method <br>
    e.g. tensor.cpu()

In [72]:
# numpy only supports CPU tensors
# torch tensors can be on CPU or GPU

# Moving tensors to GPU
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    y = torch.ones(5)
    y = y.to(device)
    z = x + y
    # z = z.numpy() # cannot convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
    z = z.to("cpu") # move to CPU first
    z = z.numpy()
    print(z)

else:
    print("CUDA not available")

CUDA not available


In [75]:
# Calculating gradients
# Gradients are used to optimize neural network parameters
# Gradients are calculated with respect to some variable
# If x is a tensor, then x.requires_grad=True indicates that x stores a gradient and that the gradient needs to be calculated with respect to x

# Example
x = torch.ones(2, 2, requires_grad=True)
print(x)

# By default, requires_grad=False


tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
